name: CI

on:
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_16.3.app/Contents/Developer

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

permissions:
  contents: read

defaults:
  run:
    working-directory: ios

jobs:
  lint:
    name: Lint
    runs-on: norionomura/swiftlint
    container: swift:6.1-noble
    timeout-minutes: 5
    steps:
      # SHA to v4
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Lint
      run: swiftlint --strict
  tests:
    name: Tests
    runs-on: macos-15
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Run Networking tests
      run: xcodebuild test -scheme Networking
      if: always()
    - name: Run Location tests
      run: xcodebuild test -scheme Location
      if: always()
    - name: Run Buildings tests
      run: xcodebuild test -scheme Buildings
      if: always()
  build:
    name: Build
    runs-on: macos-15
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Build swift project
      run: xcodebuild